name: SCSP
main: de.scspteam.scsp.src
version: 1.0
commands:
  Gs:
    usage: /<command>
    description: gibt aus was man mit dem kommando machen kann
    permission: SCSP.gs
    permission-message: test
    
   