name: SCSP
version: 0.2
description: Ein Plugin fuer Skates Community Server
website: http://skatescs.enjin.com/
author: kaizi99 und Der_Josh
main: de.scspteam.scsp.SCSP

commands:
 SCSPinfo:
  usage: /<command>
  description: Zeigt Plugin-Infos an
  permission: scsp.info
  permission-message: Du brauchst einen hoeheren Rang, um diesen Command zu benutzen!
 feed:
  usage: /<command> [player]
  description: Fuellt den Hunger von dir oder einem anderen Spieler auf
  permission: scsp.feed
  permission-message: Du brauchst einen hoeheren Rang, um diesen Command zu benutzen!
 heal:
  usage: /<command> [player]
  description: Fuellt das Leben von dir oder eines anderen Spielers auf
  permission: scsp.heal
  permission-message: Du brauchst einen hoeheren Rang, um diesen Command zu benutzen!
 skull:
  usage: /<command> [player]
  description: Gibt dir einen Kopf deines oder eines anderen Spielers
  permission: scsp.skull
  permission-message: Du brauchst einen hoeheren Rang, um diesen Command zu benutzen!
 kick:
  usage: /<command> [player]
  description: Kickt einen bestimmten Spieler
  permission: scsp.kick
  permission-message: Du brauchst einen hoeheren Rang, um diesen Command zu benutzen!
 ban:
  usage: /<command> [player]
  description: bannt den spieler vom server
  permission: scsp.ban
  permission-message: Du brauchst einen hoeheren Rang, um diesen Command zu benutzen!
 tempban:
  usage: /<command> [player] [time]
  description: bannt den spieler für eine angegebene zeit vom server
  permission: scsp.tempban
  permission-message: Du brauchst einen hoeheren Rang, um diesen Command zu benutzen!
 gs:
  usage: /<command>
  description: gibt infos über den command: /gs aus
  permission: gs.info
  permission-message: Du brauchst einen hoeheren Rang, um diesen Command zu benutzen!
 gs erklaerung:
  usage: /<command>
  description: gibt infos aus wie man /gs benutzt
  permission: gs.erklaerung
  permission-message: Du brauchst einen hoeheren Rang, um diesen Command zu benutzen! 
  